services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: alexleyoung/asap-backend:1.0
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: asap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
